# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import puzzle_worker_pb2 as puzzle__worker__pb2


class PuzzlerStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FindPuzzle = channel.unary_unary(
                '/helloworld.Puzzler/FindPuzzle',
                request_serializer=puzzle__worker__pb2.PuzzleRequest.SerializeToString,
                response_deserializer=puzzle__worker__pb2.PuzzleReply.FromString,
                )


class PuzzlerServicer(object):
    """The greeting service definition.
    """

    def FindPuzzle(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PuzzlerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FindPuzzle': grpc.unary_unary_rpc_method_handler(
                    servicer.FindPuzzle,
                    request_deserializer=puzzle__worker__pb2.PuzzleRequest.FromString,
                    response_serializer=puzzle__worker__pb2.PuzzleReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'helloworld.Puzzler', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Puzzler(object):
    """The greeting service definition.
    """

    @staticmethod
    def FindPuzzle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/helloworld.Puzzler/FindPuzzle',
            puzzle__worker__pb2.PuzzleRequest.SerializeToString,
            puzzle__worker__pb2.PuzzleReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
